import type { Signal } from './types'

export const mockSignals: Signal[] = [
  {
    id: '1',
    title: 'Track your Airbnb listing rankings, competitors and SEO insights',
    category: 'SaaS',
    summary: 'Founder looking for automated competitor price tracking across 50+ sites. Willing to pay $50-100/mo for real-time monitoring.',
    solution_exists: false,
    date: '2026-02-06',
    hn_url: 'https://news.ycombinator.com/item?id=43088871',
    signal_type: 'Direct request',
    points: 342,
    comments: 187,
  },
  {
    id: '2',
    title: 'Show HN: We built a developer-first open-source Zapier alternative',
    category: 'Automation',
    summary: "Developer frustrated with Zapier's error handling. Multiple replies agreeing. Trigger.dev positioned as reliability-first alternative.",
    solution_exists: false,
    date: '2026-02-05',
    hn_url: 'https://news.ycombinator.com/item?id=34610686',
    signal_type: 'Pain point',
    points: 489,
    comments: 231,
  },
  {
    id: '3',
    title: 'Ask HN: Would you use a serverless, pay-per-second model for AI inference?',
    category: 'Dev Tools',
    summary: 'CTO looking for unified AI spend tracking across OpenAI, Anthropic, Gemini. Only manual spreadsheet solutions suggested.',
    solution_exists: false,
    date: '2026-02-04',
    hn_url: 'https://news.ycombinator.com/item?id=44608857',
    signal_type: 'Direct request',
    points: 491,
    comments: 203,
  },
  {
    id: '4',
    title: 'Use Notion as CMS for your React pages',
    category: 'Content Tools',
    summary: 'Creator wants reliable Notion-to-static-site publishing. Existing tools break on API changes. Users asking for paid alternative.',
    solution_exists: false,
    date: '2026-02-03',
    hn_url: 'https://news.ycombinator.com/item?id=22924853',
    signal_type: 'Pain point',
    points: 267,
    comments: 145,
  },
  {
    id: '5',
    title: 'SoC 2 compliance for startups and first-timers',
    category: 'Compliance',
    summary: 'Tiny team needs SOC 2 for enterprise deals. Current tools cost $20k+. Multiple founders asking for a $500/mo alternative.',
    solution_exists: false,
    date: '2026-02-05',
    hn_url: 'https://news.ycombinator.com/item?id=39562613',
    signal_type: 'Direct request',
    points: 378,
    comments: 156,
  },
  {
    id: '6',
    title: 'Show HN: Someday, Open-Source Calendly Alternative for Gmail / Google App Script',
    category: 'Productivity',
    summary: 'Thread debating why self-hosted scheduling tools all feel half-baked. Several devs expressing willingness to pay for a polished OSS option.',
    solution_exists: true,
    date: '2026-01-30',
    hn_url: 'https://news.ycombinator.com/item?id=42027187',
    signal_type: 'Market gap',
    points: 512,
    comments: 289,
  },
  {
    id: '7',
    title: 'Ask HN: What tools are you using for AI evals? Everything feels half-baked',
    category: 'AI/ML',
    summary: 'ML engineer asking for production-grade LLM eval tools. No clear winner mentioned. Teams building custom solutions from scratch.',
    solution_exists: false,
    date: '2026-02-06',
    hn_url: 'https://news.ycombinator.com/item?id=44194187',
    signal_type: 'Direct request',
    points: 623,
    comments: 341,
  },
  {
    id: '8',
    title: 'Ask HN: Best internal tools your startup built?',
    category: 'Dev Tools',
    summary: 'Engineering lead frustrated with internal tool sprawl. Looking for a low-code platform that devs actually want to use.',
    solution_exists: true,
    date: '2026-02-01',
    hn_url: 'https://news.ycombinator.com/item?id=15804270',
    signal_type: 'Frustration',
    points: 445,
    comments: 198,
  },
  {
    id: '9',
    title: 'Ask HN: How do YC startups that are not from the US incorporate in the US?',
    category: 'SaaS',
    summary: 'Non-US founder wants streamlined US company formation without the $500 Stripe Atlas fee. Many international founders echo the sentiment.',
    solution_exists: false,
    date: '2026-02-04',
    hn_url: 'https://news.ycombinator.com/item?id=38724403',
    signal_type: 'Wish list',
    points: 387,
    comments: 212,
  },
  {
    id: '10',
    title: 'Feature Flags Missing Features',
    category: 'Dev Tools',
    summary: 'Developer asking for lightweight feature flag solutions. LaunchDarkly too expensive for small teams. Self-hosted options lack good UIs.',
    solution_exists: true,
    date: '2026-02-02',
    hn_url: 'https://news.ycombinator.com/item?id=39249337',
    signal_type: 'Direct request',
    points: 298,
    comments: 167,
  },
  {
    id: '11',
    title: 'A deep dive into email deliverability in 2024',
    category: 'SaaS',
    summary: 'Marketer frustrated with existing email warmup and deliverability tools. All feel scammy or unreliable. Market is wide open.',
    solution_exists: false,
    date: '2026-02-03',
    hn_url: 'https://news.ycombinator.com/item?id=39888383',
    signal_type: 'Frustration',
    points: 356,
    comments: 178,
  },
  {
    id: '12',
    title: 'PDF generation with HTML and CSS',
    category: 'Dev Tools',
    summary: 'Full-stack dev looking for reliable HTML-to-PDF API. Puppeteer too slow, existing APIs too expensive at scale. Want a middle ground.',
    solution_exists: true,
    date: '2026-01-29',
    hn_url: 'https://news.ycombinator.com/item?id=1433206',
    signal_type: 'Direct request',
    points: 234,
    comments: 134,
  },
  {
    id: '13',
    title: 'There is an AI code review bubble',
    category: 'AI/ML',
    summary: 'Senior engineer ranting about low-quality AI code reviews. Wants contextual understanding, not just linting. Others agree current tools miss the mark.',
    solution_exists: true,
    date: '2026-02-05',
    hn_url: 'https://news.ycombinator.com/item?id=46766961',
    signal_type: 'Pain point',
    points: 567,
    comments: 312,
  },
  {
    id: '14',
    title: 'Show HN: Freshlytics \u2013 Self-hosted analytics that respects user privacy',
    category: 'Productivity',
    summary: 'Product manager looking for privacy-first analytics. Plausible is close but missing key features. Others want better funnel tracking.',
    solution_exists: true,
    date: '2026-02-01',
    hn_url: 'https://news.ycombinator.com/item?id=21671009',
    signal_type: 'Market gap',
    points: 412,
    comments: 223,
  },
  {
    id: '15',
    title: 'AI meeting notes and transcriptions for Meet, Zoom and Teams',
    category: 'Automation',
    summary: 'Support lead wants AI that listens to customer calls and auto-creates tickets with context. Existing transcription tools lack CRM integration.',
    solution_exists: false,
    date: '2026-02-06',
    hn_url: 'https://news.ycombinator.com/item?id=40411537',
    signal_type: 'Direct request',
    points: 445,
    comments: 189,
  },
  {
    id: '16',
    title: 'A Poor Developer Onboarding Experience Can Kill Your Startup',
    category: 'Dev Tools',
    summary: 'New hire frustrated with onboarding. Wants a tool that auto-generates setup guides from repo configs. Others validate the pain.',
    solution_exists: false,
    date: '2026-02-02',
    hn_url: 'https://news.ycombinator.com/item?id=21814202',
    signal_type: 'Pain point',
    points: 389,
    comments: 201,
  },
  {
    id: '17',
    title: 'Show HN: Visual Database Schema Designer (Angular 21 and .NET 10)',
    category: 'Dev Tools',
    summary: 'Backend dev wants drag-and-drop database schema designer that generates migrations. Existing tools feel stuck in 2010.',
    solution_exists: false,
    date: '2026-02-04',
    hn_url: 'https://news.ycombinator.com/item?id=46676815',
    signal_type: 'Wish list',
    points: 534,
    comments: 267,
  },
  {
    id: '18',
    title: 'Show HN: WatchMySSL \u2013 Automated SSL Certificate Monitoring',
    category: 'Compliance',
    summary: 'DevOps engineer managing 80+ domains wants centralized SSL monitoring with Slack alerts. Current tools are either too expensive or too basic.',
    solution_exists: true,
    date: '2026-01-31',
    hn_url: 'https://news.ycombinator.com/item?id=37408368',
    signal_type: 'Direct request',
    points: 213,
    comments: 98,
  },
  {
    id: '19',
    title: 'A Content Repurposing Strategy That Works (Platform-Native, Not Asset-First)',
    category: 'Content Tools',
    summary: 'Content creator tried 5 AI repurposing tools. All produce generic output. Wants one that actually understands brand voice and context.',
    solution_exists: false,
    date: '2026-02-03',
    hn_url: 'https://news.ycombinator.com/item?id=46540989',
    signal_type: 'Frustration',
    points: 356,
    comments: 178,
  },
  {
    id: '20',
    title: 'Staging environments and microservices don\u2019t mix',
    category: 'Dev Tools',
    summary: 'Platform engineer wants ephemeral staging environments per PR. Docker Compose is not enough, Kubernetes is overkill for small teams.',
    solution_exists: true,
    date: '2026-02-06',
    hn_url: 'https://news.ycombinator.com/item?id=12539197',
    signal_type: 'Direct request',
    points: 378,
    comments: 195,
  },
]
