import type { Signal } from './types'

export const mockSignals: Signal[] = [
  {
    id: 'mock-1',
    signal_id: 'hn_ask:12345',
    source: 'hn_ask',
    title: 'AI-powered developer onboarding tools',
    narrative: 'Multiple HN threads show developers frustrated with onboarding at new companies. Manual setup docs go stale, and existing tools lack AI-driven context. A tool that auto-generates setup guides from repo configs could save teams 2-3 days per new hire.',
    one_line_hook: 'New hires waste days on outdated setup docs — AI could fix this overnight',
    key_insight: 'Onboarding pain scales with team size and repo complexity',
    categories: ['developer-tooling', 'workflow-inefficiency'],
    confidence: 'high',
    relevance_score: 9,
    content_potential: 8,
    sources_confirming: 3,
    date: '2026-02-20',
    signal_url: 'https://news.ycombinator.com/item?id=12345',
    points: 389,
    comments: 201,
    evidence: {
      google_trends: { status: 'completed', results: [], summary: '"developer onboarding tools" trending up 40% YoY', supporting: true },
      product_hunt: { status: 'completed', results: [], summary: '3 related launches in past 30 days', supporting: true },
      github: { status: 'completed', results: [], summary: 'Top repo: onboard-ai (1.2k stars, active)', supporting: true },
    },
  },
  {
    id: 'mock-2',
    signal_id: 'hn_ask:67890',
    source: 'hn_ask',
    title: 'Unified AI spend tracking dashboard',
    narrative: 'CTOs and engineering leads are struggling to track AI API costs across OpenAI, Anthropic, and Google. Only manual spreadsheet solutions exist. A unified dashboard with budget alerts and per-team breakdowns would find immediate paying customers.',
    one_line_hook: 'AI spend is the new cloud bill — and nobody has a dashboard for it yet',
    key_insight: 'Multi-provider AI usage creates blind spots in engineering budgets',
    categories: ['developer-tooling'],
    confidence: 'medium',
    relevance_score: 7,
    content_potential: 8,
    sources_confirming: 2,
    date: '2026-02-18',
    signal_url: 'https://news.ycombinator.com/item?id=67890',
    points: 491,
    comments: 203,
    evidence: {
      google_trends: { status: 'completed', results: [], summary: '"AI cost tracking" searches emerging', supporting: true },
      product_hunt: { status: 'completed', results: [], summary: 'No direct competitors found', supporting: true },
      github: { status: 'no_results', results: [], summary: 'No significant OSS solutions', supporting: false },
    },
  },
  {
    id: 'mock-3',
    signal_id: 'producthunt:11111',
    source: 'producthunt',
    title: 'Privacy-first analytics for indie hackers',
    narrative: 'Plausible and Fathom are close but missing funnel tracking and revenue attribution. Indie hackers on HN and PH repeatedly ask for a $9/mo alternative with the simplicity of Plausible but with conversion funnels built in.',
    one_line_hook: 'Indie hackers want Plausible + funnels at a price that does not hurt',
    key_insight: 'The gap is not privacy — it is funnel tracking at indie-friendly pricing',
    categories: ['demographic-market-gap'],
    confidence: 'low',
    relevance_score: 5,
    content_potential: 6,
    sources_confirming: 1,
    date: '2026-02-15',
    signal_url: 'https://www.producthunt.com/posts/example',
    points: 412,
    comments: 223,
    evidence: {
      google_trends: { status: 'completed', results: [], summary: 'Stable interest, not growing', supporting: false },
      product_hunt: { status: 'completed', results: [], summary: 'Plausible dominates, few new entries', supporting: false },
      github: { status: 'completed', results: [], summary: 'plausible/analytics (20k stars)', supporting: true },
    },
  },
]
